name: Gradle CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - '.gitattributes'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with gradle

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 17
          distribution: temurin
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar
